- id: pmid:34247231
  tags:
    - insect fungal interactions
    - ascomycota
    - genome
- id: pmid:34165331
  tags:
    - amplicon
    - ITS
    - endoliths
    - fungi
    - Joshua Tree
    - aridlands
- id: pmid:34080906
  tags:
    - cyanobacteria
    - metagenomics
    - aridlands
- id: pmid:34067070
  tags:
    - coccidioides
    - onygenales
    - RNA-seq
- id: pmid:34042486
  tags:
    - genome
    - Phytophthora
- id: pmid:33871031
  tags:
    - coccidioides
    - onygenales
    - genomics
- id: pmid:33815472
  tags:
    - black yeast
    - knufia
- id: pmid:33809619
  tags:
    - Antarctica
    - endoliths
    - amplicon
    - fungi
- id: pmid:33785623
  tags:
    - Candida
    - Clavispora lusitaniae
    - drug resistance
- id: pmid:33752605
  tags:
    - Datura
    - plant genomics
    - genome
- id: pmid:33741058
  tags:
    - metagenomics
    - Antarctica
    - endoliths
    - genome
    - MAG
- id: pmid:33686174
  tags:
    - Pneumocystis
    - comparative genomics
- id: pmid:33656416
  tags:
    - Apicomplexian
    - RNA binding
    - Evolution
- id: pmid:33607033
  tags:
    - fungi
    - phylogenomics
    - systematics
    - evolution
- id: pmid:33597172
  tags:
    - Aspergillus fumigatus
    - Cystic Fibrosis
- id: pmid:33593969
  tags:
    - Aspergillus fumigatus
    - biofilm
    - RNA-seq
- id: pmid:33592192
  tags:
    - Geosiphon
    - AMF
    - zygomycete
    - genome
    - comparative genomics
- id: pmid:33585864
  tags:
    - genome
    - Pleurotus
- id: pmid:33585863
  tags:
    - genome
    - Pleurotus
- id: pmid:33547391
  tags:
    - fungi
    - phylogenomics
    - zygomycete
    - chytrid
    - evolution
    - metagenomics
    - genome
- id: pmid:33364917
  tags:
    - genome
    - zygomycete
    - Mortierellaceae
    - phylogenomics
- id: pmid:33355923
  tags:
    - Suillus
    - basidomycota
    - comparative genomics
    - phylogenomics
- id: pmid:33352712
  tags:
    - black yeast
    - review
- id: pmid:33232202
  tags:
    - endoliths
    - review
    - fungi
    - rock
- id: pmid:33200960
  tags:
    - phylogenomics
    - Fusarium
- id: pmid:33155518
  tags:
    - Sporothrix
    - genome
    - comparative genomics
- id: pmid:33138786
  tags:
    - Neurospora
    - phenotype
- id: pmid:33020276
  tags:
    - Rice
    - transposon
    - mPing
- id: pmid:32938701
  tags:
    - Fusarium
    - phylogeny
    - taxonomy
    - systematics
- id: pmid:32902066
  tags:
    - soil microbiome
    - ITS
    - 16S
    - amplicon
    - environmental microbiology
- id: pmid:32900807
  tags:
    - mycovirus
    - chytrid
    - zygomycete
    - virus
- id: pmid:32883786
  tags:
    - review
    - MRA
- id: pmid:32727924
  tags:
    - phylogenomics
    - Basidiobolus
    - HGT
    - fungi
    - zygomycete
- id: pmid:32660385
  tags:
    - review
    - fungi
    - phylogeny
    - phylogenomics
- id: pmid:32585947
  tags:
    - amplicon
    - culture
    - Antarctica
    - endoliths
- id: pmid:32573682
  tags:
    - amplicon
    - ITS
    - 16S
    - fungi
    - aridlands
    - biological crust
- id: pmid:32555716
  tags:
    - insect fungal interactions
    - review
    - zygomycete
    - Entomophthomycotina
- id: pmid:32412847
  tags:
    - Massospora
    - zygomycete
    - systematics
    - Entomophthomycotina
- id: pmid:32389308
  tags:
    - Friemannomyces
    - black yeast
    - Antarctica
    - genome
- id: pmid:32371596
  tags:
    - review
    - fungi
    - disease
    - wildlife disease
- id: pmid:32241854
  tags:
    - genome
    - Rhodotorula
    - Antarctica
- id: pmid:32161129
  tags:
    - nematode trapping fungi
    - genome
    - population genomics
- id: pmid:32139564
  tags:
    - metagenomics
    - endoliths
    - Antarctica
- id: pmid:32041249
  tags:
    - Antarctica
    - endoliths
    - fungi
    - amplicon
- id: pmid:31900675
  tags:
    - Africa
    - spore
    - fungi
- id: pmid:31871487
  tags:
    - millipede
    - culture-based
    - zygomycete
- id: pmid:31768192
  tags:
    - Massospora
    - zygomycete
    - genome
    - insect fungal interactions
- id: pmid:31647694
  tags:
    - Fusarium
    - plant pathology
    - tool
- id: pmid:31632357
  tags:
    - zygomycete
    - tool
    - bacteria fungi interactions
- id: pmid:31548684
  tags:
    - Aspergillus fumigatus
    - biofilm
    - disease
    - hypoxia
- id: pmid:31518652
  tags:
    - Fusarium
    - avocado
    - plant pathology
- id: pmid:31488541
  tags:
    - review
    - MRA
- id: pmid:31455637
  tags:
    - HGT
    - systematics
    - AGF
    - Neocallimastigomycota
    - transcriptome
- id: pmid:31416856
  tags:
    - genome
    - coccidioides
- id: pmid:31393667
  tags:
    - Antarctica
    - amplicon
    - ITS
    - 16S
- id: pmid:31156574
  tags:
    - proteomics
    - black yeast
    - extremophile
- id: pmid:31126947
  tags:
    - HGT
    - Neocallimastigomycota
    - AGF
- id: pmid:31072892
  tags:
    - Exophiala
    - extremophile
    - Antarctica
- id: pmid:30987585
  tags:
    - tool
    - genomics
- id: pmid:30837337
  tags:
    - review
    - marine fungi
- id: pmid:30778188
  tags:
    - epigenetics
    - fungi
    - 5mC
    - methylation
- id: pmid:30733435
  tags:
    - transposon
    - Rice
    - mPing
- id: pmid:30701257
  tags:
    - Verticllium
    - genome
- id: pmid:30697917
  tags:
    - systematics
- id: pmid:30673440
  tags:
    - Fusarium kuroshium
    - avocado
    - AFC
- id: pmid:30639767
  tags:
    - Zoopagales
    - Zoopagomycota
    - zygomycete
    - phylogenomics
    - systematics
- id: pmid:30539259
  tags:
    - Aspergillus nidulans
    - proteomics
    - space fungi
    - ISS
- id: pmid:30485448
  tags:
    - phylogenomics
    - systematics
    - zygomycete
    - Endogone
- id: pmid:30389707
  tags:
    - Candida
    - Clavispora lustianiae
    - drug resistance
- id: pmid:30293061
  tags:
    - insect
    - RNA-seq
    - venom
- id: pmid:30246146
  tags:
    - Aspergillus niger
    - population genomics
    - ISS
    - space fungi
- id: pmid:30111619
  tags:
    - Entomophthomycotina
    - protease
    - Entomopthora muscae
- id: pmid:30016947
  tags:
    - genome
    - Thraustochytrid
    - comparative genomics
- id: pmid:30008702
  tags:
    - unclassified
- id: pmid:29865244
  tags:
    - unclassified
- id: pmid:29764946
  tags:
    - unclassified
- id: pmid:29764372
  tags:
    - unclassified
- id: pmid:29739910
  tags:
    - unclassified
- id: pmid:29675967
  tags:
    - unclassified
- id: pmid:29674435
  tags:
    - unclassified
- id: pmid:29371508
  tags:
    - unclassified
- id: pmid:29321239
  tags:
    - unclassified
- id: pmid:29211832
  tags:
    - unclassified
- id: pmid:29158416
  tags:
    - unclassified
- id: pmid:29023459
  tags:
    - unclassified
- id: pmid:28917057
  tags:
    - unclassified
- id: pmid:28916147
  tags:
    - unclassified
- id: pmid:28876195
  tags:
    - unclassified
- id: pmid:28820125
  tags:
    - unclassified
- id: pmid:28684563
  tags:
    - unclassified
- id: pmid:28500048
  tags:
    - unclassified
- id: pmid:28481340
  tags:
    - unclassified
- id: pmid:28462022
  tags:
    - unclassified
- id: pmid:28176784
  tags:
    - unclassified
- id: pmid:28149701
  tags:
    - unclassified
- id: pmid:30682305
  tags:
    - unclassified
- id: pmid:27738200
  tags:
    - unclassified
- id: pmid:27554660
  tags:
    - unclassified
- id: pmid:27294409
  tags:
    - unclassified
- id: pmid:27048799
  tags:
    - unclassified
- id: pmid:27034999
  tags:
    - unclassified
- id: pmid:26976598
  tags:
    - unclassified
- id: pmid:26903035
  tags:
    - unclassified
- id: pmid:26305593
  tags:
    - unclassified
- id: pmid:26109355
  tags:
    - unclassified
- id: pmid:25819009
  tags:
    - unclassified
- id: pmid:25805857
  tags:
    - unclassified
- id: pmid:25750214
  tags:
    - unclassified
- id: pmid:25427217
  tags:
    - unclassified
- id: pmid:25351875
  tags:
    - unclassified
- id: pmid:25330340
  tags:
    - unclassified
- id: pmid:25143134
  tags:
    - unclassified
- id: pmid:24912000
  tags:
    - unclassified
- id: pmid:24813190
  tags:
    - unclassified
- id: pmid:24743168
  tags:
    - unclassified
- id: pmid:24299411
  tags:
    - unclassified
- id: pmid:24285193
  tags:
    - unclassified
- id: pmid:24152717
  tags:
    - unclassified
- id: pmid:24068976
  tags:
    - unclassified
- id: pmid:23961317
  tags:
    - unclassified
- id: pmid:23951101
  tags:
    - unclassified
- id: pmid:23932404
  tags:
    - unclassified
- id: pmid:23928422
  tags:
    - unclassified
- id: pmid:23650365
  tags:
    - unclassified
- id: pmid:23576519
  tags:
    - unclassified
- id: pmid:23530226
  tags:
    - unclassified
- id: pmid:23514374
  tags:
    - unclassified
- id: pmid:23341551
  tags:
    - unclassified
- id: pmid:23186325
  tags:
    - unclassified
- id: pmid:22718849
  tags:
    - unclassified
- id: pmid:22593224
  tags:
    - unclassified
- id: pmid:22072962
  tags:
    - unclassified
- id: pmid:22064857
  tags:
    - unclassified
- id: pmid:21750257
  tags:
    - unclassified
- id: pmid:21304167
  tags:
    - unclassified
- id: pmid:21268975
  tags:
    - unclassified
- id: pmid:20885784
  tags:
    - unclassified
- id: pmid:20836076
  tags:
    - unclassified
- id: pmid:20675579
  tags:
    - unclassified
- id: pmid:20626842
  tags:
    - unclassified
- id: pmid:20622885
  tags:
    - unclassified
- id: pmid:20601044
  tags:
    - unclassified
- id: pmid:20547848
  tags:
    - unclassified
- id: pmid:20516208
  tags:
    - unclassified
- id: pmid:20386741
  tags:
    - unclassified
- id: pmid:20126439
  tags:
    - unclassified
- id: pmid:19788875
  tags:
    - unclassified
- id: pmid:19717792
  tags:
    - unclassified
- id: pmid:19161465
  tags:
    - unclassified
- id: pmid:19085333
  tags:
    - unclassified
- id: pmid:18852473
  tags:
    - unclassified
- id: pmid:18322534
  tags:
    - unclassified
- id: pmid:18313909
  tags:
    - unclassified
- id: pmid:18294377
  tags:
    - unclassified
- id: pmid:18287711
  tags:
    - unclassified
- id: pmid:17949488
  tags:
    - unclassified
- id: pmid:17337636
  tags:
    - unclassified
- id: pmid:17320905
  tags:
    - unclassified
- id: pmid:17183716
  tags:
    - unclassified
- id: pmid:17148473
  tags:
    - unclassified
- id: pmid:17121679
  tags:
    - unclassified
- id: pmid:17080091
  tags:
    - unclassified
- id: pmid:17051209
  tags:
    - unclassified
- id: pmid:16988423
  tags:
    - unclassified
- id: pmid:16963629
  tags:
    - unclassified
- id: pmid:16962256
  tags:
    - unclassified
- id: pmid:16899494
  tags:
    - unclassified
- id: pmid:16682456
  tags:
    - unclassified
- id: pmid:16606443
  tags:
    - unclassified
- id: pmid:16222245
  tags:
    - unclassified
- id: pmid:16143628
  tags:
    - unclassified
- id: pmid:16077014
  tags:
    - unclassified
- id: pmid:15854223
  tags:
    - unclassified
- id: pmid:15470254
  tags:
    - unclassified
- id: pmid:15356276
  tags:
    - unclassified
- id: pmid:14624247
  tags:
    - unclassified
- id: pmid:12716998
  tags:
    - unclassified
- id: pmid:12368254
  tags:
    - unclassified
- id: pmid:12368253
  tags:
    - unclassified
- id: pmid:11743579
  tags:
    - unclassified
